name: Remote ls and send mail

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  remote-ls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Krok 1: testowe logowanie do SSH hasłem
      - name: Test SSH connection
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: "4.210.108.59"
          username: "kurs"
          password: "3Szkolenie.admin2"
          port: 22
          script: |
            echo "Połączenie SSH działa poprawnie"
            hostname
            whoami

      # Krok 2: właściwe polecenie ls -la
      - name: Run ls -la on remote host
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: "4.210.108.59"
          username: "kurs"
          password: "3Szkolenie.admin2"
          port: 22
          script: |
            ls -la

      # Krok 3: wysyłka maila
      - name: Send email with repo name
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: "mail.abix.info.pl"
          server_port: "465"
          secure: true
          username: "alx-kurs@abix.info.pl"
          password: "74a93d0649cc71c05759c301b5c50b1c"
          subject: "Repo workflow notification"
          to: "adam@jurkiewicz.tech"
          from: "alx-kurs@abix.info.pl"
          body: |
            Workflow został uruchomiony z repozytorium:
            ${{ github.repository }}
